# Numpy Array and Basics

In [11]:
import numpy as np

### Creating Arrays from list

In [12]:
arr_1d = np.array([1,2,3,4])
print(f"1-D Array : {arr_1d}")

arr_2d = np.array([[1,2,3],[4,5,6]])
print(f"2-D Array : {arr_2d}")

1-D Array : [1 2 3 4]
2-D Array : [[1 2 3]
 [4 5 6]]


### List Vs Numpy Array

In [13]:

py_list = [1,2,3,4]
print(py_list)
print("Python list multiplication : ",py_list * 2)

np_array = np.array([1,2,3,4])
print(np_array)
print("Python array multiplication : ",np_array * 2)



import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
end = time.time()
print("\n")
print(f"List operetion time : {end - start}")

start = time.time()
np_array = np.arange(1000000)*2
end = time.time()
print("\n")
print(f"Numpy operetion time : {end - start}")


[1, 2, 3, 4]
Python list multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
[1 2 3 4]
Python array multiplication :  [2 4 6 8]


List operetion time : 0.055527687072753906


Numpy operetion time : 0.005555152893066406


### Creating Array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros)

print("\n")

ones = np.ones((2,4))
print("Ones Array : \n",ones)

print("\n")

full = np.full((2,2),7)
print("Full Array : \n",full)

print("\n")

random = np.random.random((2,2))
print("Random Array : \n",random)

print("\n")

sequence = np.arange(0,10,2)
print("Sequence Array : \n",sequence)


Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones Array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Full Array : 
 [[7 7]
 [7 7]]


Random Array : 
 [[0.11957394 0.45868245]
 [0.20387823 0.13671315]]


Sequence Array : 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [ ]:
Vector = np.array([1,2,3])
print("Vector : ", Vector)

Matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix : \n", Matrix)

Tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor : \n", Tensor)


Vector :  [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array : \n", arr)
print("Shape of Array :", arr.shape) 
print("Dimension of Array :", arr.ndim)
print("Size of Array :", arr.size)
print("Data Type of Array :", arr.dtype)


Array : 
 [[1 2 3]
 [4 5 6]]
Shape of Array : (2, 3)
Dimension of Array : 2
Size of Array : 6
Data Type of Array : int64


### Array Reshaping 

In [7]:
arr = np.arange(1,13)
print("Original Array :", arr)

print("\n")

reshape = arr.reshape((3,4))
print("Reshape Array :\n", reshape)

print("\n")

flattend = reshape.flatten()
print("Flattened Array :", flattend)

print("\n")

ravel = reshape.ravel()#reval return veiw instaed of copy
print("Ravelled Array :", ravel)

print("\n")

transposed = reshape.T
print("Transposed Array :\n", transposed)

Original Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


Reshape Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Flattened Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


Ravelled Array : [ 1  2  3  4  5  6  7  8  9 10 11 12]


Transposed Array :
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
