# Numpy Array Operation :

In [ ]:
import numpy as np

In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print ("Basic Slicing :",arr[2:7])
print ("With Step Slicing :",arr[0:10:2])
print ("Negative Slicing :",arr[-8:-5])

Basic Slicing : [3 4 5 6 7]
With Step Slicing : [1 3 5 7 9]
Negative Slicing : [3 4 5]


In [72]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("2D Array :\n", arr_2D)
print("Specific Element :",arr_2D[0,2])
print("Entrie Row :",arr_2D[1,:])
print("Entrie Collumn :",arr_2D[:,1])

2D Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific Element : 3
Entrie Row : [4 5 6]
Entrie Collumn : [2 5 8]


# Sorting :

In [95]:
unsorted = np.array([2,8,6,4,3,1,2,9])

print("Unsorted Array :",unsorted)

print("Sorted Array :",np.sort(unsorted))


print("\n")


arr_2D_unsorted = np.array([[2,5,9],[1,4,3],[8,6,2]])

print("Unsorted 2D Array :\n",arr_2D_unsorted)

print("Sorted 2D Array :\n",np.sort(arr_2D_unsorted))

print("Sorted 2D Array by Collumn :",np.sort(arr_2D_unsorted[:,1]))

print("Sorted 2D Array by Row :",np.sort(arr_2D_unsorted[1,:]))

# sort by axis

print("Sorted 2D Array by Row :\n",np.sort(arr_2D_unsorted,axis = 1))

print("Sorted 2D Array by Collumn :\n",np.sort(arr_2D_unsorted,axis = 0))


Unsorted Array : [2 8 6 4 3 1 2 9]
Sorted Array : [1 2 2 3 4 6 8 9]


Unsorted 2D Array :
 [[2 5 9]
 [1 4 3]
 [8 6 2]]
Sorted 2D Array :
 [[2 5 9]
 [1 3 4]
 [2 6 8]]
Sorted 2D Array by Collumn : [4 5 6]
Sorted 2D Array by Row : [1 3 4]
Sorted 2D Array by Row :
 [[2 5 9]
 [1 3 4]
 [2 6 8]]
Sorted 2D Array by Collumn :
 [[1 4 2]
 [2 5 3]
 [8 6 9]]


# Filter :

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,10])

even_number = number[number % 2 == 0]
print("Even Numbers :",even_number)

# Filter with Mask

mask = number % 2 != 0
odd_number = number[mask]
print("Odd Numbers :",odd_number)

Even Numbers : [ 2  4  6  8 10]
Odd Numbers : [1 3 5 7 9]


# Fancy Indexing Vs np.where() :

In [22]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4,6,8]
print("Indexing :",number[indices]) 

where_result = np.where(number >5)
print("np where :",number[where_result])

Indexing : [1 3 5 7 9]
np where : [ 6  7  8  9 10]


In [50]:
condition_array = np.where(number > 5, number*2,number)
#It is worked like given below code
# if number > 5:
#    number*2
# else:
#    number
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


# Adding and Removing Data :

In [49]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

combaine_array = np.concatenate((arr_1, arr_2))
print("Combine Array :",combaine_array)


Combine Array : [1 2 3 4 5 6]


### Array Compatibilty :

In [78]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatiblity Shapes :",a.shape == b.shape == c.shape)


Compatiblity Shapes : True


### Use of stake :

In [77]:
original = np.array([[1,2],[3,4]])
print("Original :\n",original)

print("\n")

new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))
print("Add New Row :\n",with_new_row)

print("\n")

new_col = ([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("Add New Collumn :\n",with_new_col)

Original :
 [[1 2]
 [3 4]]


Add New Row :
 [[1 2]
 [3 4]
 [5 6]]


Add New Collumn :
 [[1 2 7]
 [3 4 8]]


### Delete Data from Array :

In [91]:
arr = np.array([1,8,9,7])
print("Original Array :",arr)

delete = np.delete(arr,1)
print("After Delete :",delete)

delete = np.delete(arr,[1,3])
print("After Delete :",delete)


Original Array : [1 8 9 7]
After Delete : [1 9 7]
After Delete : [1 9]
